version: "3"
services:

  db:
    image: postgres:11-alpine
    command: postgres -c 'max_connections=300'
    environment:
      POSTGRES_DB: training
      POSTGRES_PASSWORD: training
      POSTGRES_USER: training
    ports:
      - "5432:5432"
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - hrt2-training-db-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hrt2@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: hrt2
    restart: unless-stopped
    volumes:
      - hrt2-training-pgadmin:/var/lib/pgadmin

volumes:
  hrt2-training-db-data:
  hrt2-training-pgadmin:
